/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lidong_demo_ndkdemo_NdkTest */

#ifndef _Included_com_lidong_demo_ndkdemo_NdkTest
#define _Included_com_lidong_demo_ndkdemo_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lidong_demo_ndkdemo_NdkTest
 * Method:    add
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_lidong_demo_ndkdemo_NdkTest_add
  (JNIEnv *, jclass, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
